data_path: F:/Datasets/lipreading/  #
char_path: dictionary/zh-cn/icslr.txt
train: labels/icslrAuth/icslr_sentence_icslr_video_seg24s_val112.csv  # icslr_sentence_icslr_video_seg24s_train
val: labels/icslrAuth/icslr_sentence_icslr_video_seg24s_val112.csv
test: labels/icslrAuth/icslr_sentence_icslr_video_seg24s_test.csv  # icslr_sentence_icslr_video_seg24s_test
data_utils:
  rate_ratio: 640
  max_frames: 1200 #1800
  max_frames_val: 500 #500
  dataset_type: avdataset
  batch_size: 64

